### PR TITLE
BDS-31: Fix for adding the encoded priority to the APDU

### PR DESCRIPTION
**Pull request by gofling**

### CODE REVIEW

**Comment by SteveOss** [comment]
See we took a cut at 0.8.0 of the stack. Is now at 0.8.6, at some point need to review and merge
fixes from the upstream project.

**Comment by gofling** [comment]
This version of the stack is 0.8.5, but yes, we should upgrade to 0.8.6 at some point

**Comment by SteveOss** [comment]
As 0.8.6 should just be a bug fix, worth doing before our release.

**Review by SteveOss — APPROVED** [review]
LGTM

**Pull request merged**
